# This is a basic workflow to help you get started with Actions

name: setup-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ master ]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: install environment
      run: bash setup.sh

    # Runs a set of commands using the runners shell
    - name: Test rcsserver3d
      run: |
        export LD_LIBRARY_PATH=/usr/local/lib/simspark:/usr/local/lib/rcssserver3d
        timeout -s 9 10 rcssserver3d
